# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
[
	
	 "Bench Press",
	 "Cable Crossover",
	 "Decline Bench Press",
   "Floor Press",
 	 "Incline Bench Press",
	 "Pullover",
	 "Push Up",
   "Stretching",
   "Clean Barbell",
   "Clean & Jerk",
   "Hang Clean",
   "Hang Snatch",
   "Overhead Squat",
   "Power Clean",
   "Power Snatch",
   "Snatch",
   "Snatch Pull",
   "Split Jerk",
	 "Arnold Press",
	 "Front Raise",
	 "Lateral Raise",
   "Overhead Press",
   "Overhead Press",
	 "Overhead Press - Single Arm",
	 "Push Press",
   "Seated Overhead Press",
   "Shrug",
	 "Upright Row",
	 "Bent Over One Arm Row",
	 "Bent Over Row",
	 "Chin Up",
	 "Deadlift",
	 "Good Morning",
	 "Lat Pulldown",
	 "Lat Pulldown - Wide Grip",
	 "Lat Pulldown - Underhand",
	 "Muscle Up",
	 "Pull Up",
	 "Pull Up - One Arm",
	 "Seated Row",
	 "Stiff Leg Deadlift",
	 "T-Bar Row",
	 "Bicep Curl",
	 "Hammer Curl ",
	 "Incline Curl",
	 "Preacher Curl ",
	 "Ring Dips ",
	 "Skullcrusher ",
	 "Tricep Dip",
	 "Tricep Extension",
	 "Tricep Pushdown",
	 "Ab Wheel",
	 "Bicycle Crunch",
	 "Crunch",
	 "Hanging Knee Raise",
   "Hanging Leg Raise",
   "Plank",
   "Russian Twist",
   "Side Plank",
   "Sit Up",
   "Superman",
   "Toes-To-Bar",
   "V-Up",
   "Windshield Wiper",
	 "Box Jump",
	 "Front Squat",
	 "Goblet Squat",
	 "Hip Thrust",
	 "Jump Squat",
	 "Leg Press",
	 "Lunge(Barbell)",
	 "Lunge - Reverse",
	 "Leg Curl",
   "Mountain Climber",
   "Pause Squat(Barbell)",
   "Pistol Squat",
   "Seated Calf Raise",
   "Squat",
   "Standing Calf Raise",
   "Step Up",
   "Stiff Leg Deadlift",
   "Burpee",
   "Kettlebell Swing",
   "Muscle Up - Bar",
   "Muscle Up - Rings",
   "Thruster(Barbell)",
   "Planche",
   "Wall Ball",
   "Jump Rope",
   "Rowing",
   "Running",
   "Running - Treadmill"
].each do |exercise|
  Exercise.create(name: exercise)
end
